### ISSUE TITLE
[Test Case Failure]:   for the test `GeminiSchemaConverter_test.test_convert`

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#113]
### Test Case

tests/schema_converters/GeminiSchemaConverter_test.py

### Root Cause

The test is likely failing due to a TypeError
```
raise TypeError(f'Object of type {o.__class__.__name__} '
                        f'is not JSON serializable')
E       TypeError: Object of type FunctionDeclaration is not JSON serializable
```

### Potential Solutions

Check the return type inside  `/ swarmauri/standard/schema_converters/concrete/GeminiSchemaConverter.GeminiSchemaConverter`

### Type of Test Case

Unit

**Comment by cobycloud** [comment]
https://github.com/swarmauri/swarmauri-sdk/blob/master/swarmauri/standard/schema_converters/concrete/GeminiSchemaConverter.py includes non-serializable objects.

`GeminiToolModel` uses the `GeminiSchemaConverter` successfully right now.

If we refactor the `GeminiSchemaConverter` to make it JSON serializable, then we must update the `GeminiToolModel` to handle this change also.

**Comment by cobycloud** [comment]
documentation on function calling for Gemini:

https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/function-calling

**Comment by cobycloud** [comment]
https://ai.google.dev/gemini-api/docs/function-calling

**Comment by cobycloud** [comment]
After merging #159 we are seeing the following error messages:

```python
tests/schema_converters/GeminiSchemaConverter_test.py::test_convert 
-------------------------------- live log call ---------------------------------
[{'name': 'AdditionTool', 'description': 'This tool has two numbers together', 'parameters': {'type': <Type.OBJECT: 6>, 'properties': {'y': {'type': <Type.INTEGER: 3>, 'description': 'The right operand'}, 'x': {'type': <Type.INTEGER: 3>, 'description': 'The left operand'}}, 'required': ['x', 'y']}}]
FAILED    
```

```python
FAILED tests/llms/GeminiToolModel_test.py::test_agent_exec - ValueError: Protocol message Schema has no "type" field.
FAILED tests/schema_converters/GeminiSchemaConverter_test.py::test_convert - TypeError: Object of type Repeated is not JSON serializable
```

**Comment by cobycloud** [comment]
#163 this resolved the GeminiSchemaConverter failure
