### ISSUE TITLE
[Test Case Failure]: FAILED tests/embeddings/TfidfEmbedding_test.py::test_infer_vector

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#119]
### Test Case

FAILED tests/embeddings/TfidfEmbedding_test.py::test_infer_vector

### Root Cause

FAILED tests/embeddings/TfidfEmbedding_test.py::test_infer_vector - TypeError: TfidfEmbedding.transform() missing 1 required positional argument: 'documents'

### Potential Solutions

Fist
check `standard/embeddings/concrete/TfidfEmbedding`'s interface.

Then
check `TfidfEmbedding_test.py::test_infer_vector`'s test case.

Finally, 
1. update the test case to use keyword argument. 
2. update TfidfEmbedding to use a keyword argument.

### Type of Test Case

Unit

**Comment by RafaelJohn9** [comment]
The PR linked above fixes  the  missing argument error by changing  the infer_vector to use the `fit_transform` instead of `transform` method
