### ISSUE TITLE
[Test Case Failure]: tests/llms/ShuttleAIModel_test.py

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#146]
### Test Case

tests/llms/ShuttleAIModel_test.py

### Root Cause

Assertion errors:  AI's output does not contain the expected keywords

### Potential Solutions

Refining the current  test input in order to make the AI to have the asserted keywords

### Type of Test Case

Unit

**Comment by cobycloud** [comment]
the following tests are all failing:

`Shuttle AI on test_nonpreamble_system_context, test_preamble_system_context, test_multiple_system_context`

**Comment by cobycloud** [comment]
this was reported in: https://github.com/swarmauri/swarmauri-sdk/issues/118
