### ISSUE TITLE
[Design Feedback]: enhance Vector Stores to Support Both Local and Cloud-Based Storage Configurations

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#217]
### Description

The current  vector stores are mainly made to work locally but  a cloud based approach is also needed

Here are some recommendations:
- `api_key`  could be an optional trait on the main class. 
- `url` could service both references to `local file paths` and `cloud endpoints`
- `distance...` could be an `object...` or it could be a `configuration` on the cloud
- `embedder` - we need to see if this is only set when we use `local vector store databases`... or if there might be a time when we can select an embedder when we use a `third party vector database`.

**Comment by RafaelJohn9** [comment]
When implementing the `SqliteVectorStore`, a key challenge encountered was the implementation of the `retrieve method`. The current `abstract class` specifies a return type of  `str`, which necessitates the use of an `embedder`. However, since the embedder has not yet been implemented, this has raised issues in the development process. And may affect `current vector store design`

**Comment by cobycloud** [comment]
1. please refer to the vector db and embedding tickets that we have, which include third party libraries that we would like to integrate.
2. research their APIs and configuration parameters in detail
3. make a recommendation for a base class and mixins that can service local and cloud based vector databases
