### ISSUE TITLE
 [Code Hygiene]: migrate excess interface sets out of core/vector_stores/*

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#220]
### Code Area

core/vector_stores/*

### Hygiene Issue Description

please go through the core interface sets for the vector stores and report which ones are in use commonly, rarely, and not at all

### Motivation

we have clutter here

### Potential Solutions

move to experimental

### Affected Areas

Core

### Priority

Low

**Comment by RafaelJohn9** [comment]
| Interface                    | Usage |
|------------------------------|-------|
| `IVectorStore`               | 12    |
| `ISimilarity`                |  9    |
| `IVectorNorm`                | 2    |
| `IVectorStoreRetrieve`       | 3    |
| `IVectorStoreSaveLoad`       | 3     |
| `IAngleBetweenVectors`       | 1     |
| `IDecompose`                 | 1     |
| `IDivergence`                | 1     |
| `IGradient`                  | 1     |
| `IOrthogonalProject`         | 1     |
| `IProject`                   | 1     |
| `IReflect`                   | 1     |
| `ISimiliarityQuery`          | 1     |
| `IVectorArithmetic`          | 1     |
| `IVectorBasisCheck`          | 1     |
| `IVectorLinearCombination`   | 1     |
| `IVectorRotate`              | 1     |
| `IVectorSpan`                | 1     |

**1 is for its definition**

**Comment by RafaelJohn9** [comment]
Some vector stores interfaces are not being utilized, hence the need to transfer them from swarmauri, to experimental.

The ones with `0` class call need to be transfered to `/pkgs/experimental/swarmauri_experimental/vector_stores/core`

**Comment by MichaelDecent** [comment]
files needed to be migrated

- [ ] IAngleBetweenVectors 	0
- [ ] IDecompose 	0
- [ ] IDivergence 	0
- [ ] IGradient 	0
- [ ] IOrthogonalProject 	0
- [ ] IProject 	0
- [ ] IReflect 	0
- [ ] ISimiliarityQuery 	0
- [ ] IVectorArithmetic 	0
- [ ] IVectorBasisCheck 	0
- [ ] IVectorLinearCombination 	0
- [ ] IVectorRotate 	0
- [ ] IVectorSpan

**Comment by MichaelDecent** [comment]
[](https://github.com/swarmauri/swarmauri-sdk/pull/597)
