### ISSUE TITLE
[Test Case Failure]: test_call

### ISSUE THREAD

**Issue by MichaelDecent** [swarmauri/swarmauri-sdk#272]
### Test Case

tests/tools

### Pytest Logs

```
FAILED tests/tools/AutomatedReadabilityIndex_test.py::test_call - TypeError: AutomatedReadabilityIndexTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/ColemanLiauIndex_test.py::test_call - TypeError: ColemanLiauIndexTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/DaleChallReadability_test.py::test_call - TypeError: DaleChallReadabilityTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/FleschReadingEase_test.py::test_call - TypeError: FleschReadingEaseTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/GunningFogIndex_test.py::test_call - TypeError: GunningFogIndexTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/LexicalDensity_test.py::test_call - TypeError: LexicalDensityTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/SMOGIndex_test.py::test_call - TypeError: SMOGIndexTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/SentenceComplexity_test.py::test_call - TypeError: SentenceComplexityTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/TextLength_test.py::test_call - TypeError: TextLengthTool.__call__() takes 2 positional arguments but 3 were given
FAILED tests/tools/FleschKincaid_test.py::test_call - TypeError: FleschKincaidTool.__call__() takes 2 positional arguments but 3 were given
```
AND

`FAILED tests/tools/MatplotlibTool_test.py::test_call - TypeError: MatplotlibTool.__call__() missing 1 required positional argument: 'y_data'`

### Root Cause

`TypeError: __call__() takes 2 positional arguments but 3 were given` AND ` TypeError: MatplotlibTool.__call__() missing 1 required positional argument: 'y_data`

### Potential Solutions

Make sure  the method ` __call__` takes two positional arguments.

### Type of Test Case

Unit

**Comment by cobycloud** [comment]
This is an issue with the test files and not with the components themselves. `::test_call`` needs to be adapted to each of the tools now.


- [ ] ILED tests/tools/AutomatedReadabilityIndex_test.py::test_call - TypeError: AutomatedReadabilityIndexTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/ColemanLiauIndex_test.py::test_call - TypeError: ColemanLiauIndexTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/DaleChallReadability_test.py::test_call - TypeError: DaleChallReadabilityTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/FleschReadingEase_test.py::test_call - TypeError: FleschReadingEaseTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/GunningFogIndex_test.py::test_call - TypeError: GunningFogIndexTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/LexicalDensity_test.py::test_call - TypeError: LexicalDensityTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/SMOGIndex_test.py::test_call - TypeError: SMOGIndexTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/SentenceComplexity_test.py::test_call - TypeError: SentenceComplexityTool.__call__() takes 2 positional arguments but 3 were given
- [ ] FAILED tests/tools/Text

**Comment by MichaelDecent** [comment]
Okay.

**Comment by cobycloud** [comment]
team worked through these

**Comment by JustusOmbok** [comment]
- [ ] FAILED tests/tools/AutomatedReadabilityIndex_test.py::test_call - AttributeError: 'AutomatedReadabilityIndexTool' object has no attribute 'validate_input'

- [ ] FAILED tests/tools/ColemanLiauIndex_test.py::test_call - AttributeError: 'ColemanLiauIndexTool' object has no attribute 'validate_input'

- [ ] FAILED tests/tools/DaleChallReadability_test.py::test_call - assert 7.98 == 6.5 ± 6.5e-02

  comparison failed
  Obtained: 7.98
  Expected: 6.5 ± 6.5e-02

- [ ] FAILED tests/tools/FleschKincaid_test.py::test_call - TypeError: FleschKincaidTool.__call__() takes 2 positional arguments but 3 were given

- [ ] FAILED tests/tools/GunningFogTool_test.py::test_call - AttributeError: 'GunningFogTool' object has no attribute 'validate_input'

- [ ] FAILED tests/tools/LexicalDensity_test.py::test_call - AttributeError: module 'textstat' has no attribute 'is_lexical_word'

- [ ] FAILED tests/tools/MatplotlibTool_test.py::test_call - TypeError: MatplotlibTool.__call__() missing 1 required positional argument: 'y_data'

- [ ] FAILED tests/tools/RequestsTool_test.py::test_call - AttributeError: 'int' object has no attribute 'lower'

- [ ] FAILED tests/tools/TextLength_test.py::test_call - TypeError: TextLengthTool.__call__() takes 2 positional arguments but 3 were given

**Comment by MichaelDecent** [comment]
> * [ ]  FAILED tests/tools/AutomatedReadabilityIndex_test.py::test_call - AttributeError: 'AutomatedReadabilityIndexTool' object has no attribute 'validate_input'
> 
>     * [ ]  FAILED tests/tools/ColemanLiauIndex_test.py::test_call - AttributeError: 'ColemanLiauIndexTool' object has no attribute 'validate_input'
> 
>     * [ ]  FAILED tests/tools/DaleChallReadability_test.py::test_call - assert 7.98 == 6.5 ± 6.5e-02
>       comparison failed
>       Obtained: 7.98
>       Expected: 6.5 ± 6.5e-02
> 
>     * [x]  FAILED tests/tools/FleschKincaid_test.py::test_call - TypeError: FleschKincaidTool.**call**() takes 2 positional arguments but 3 were given
> 
>     * [ ]  FAILED tests/tools/GunningFogTool_test.py::test_call - AttributeError: 'GunningFogTool' object has no attribute 'validate_input'
> 
>     * [ ]  FAILED tests/tools/LexicalDensity_test.py::test_call - AttributeError: module 'textstat' has no attribute 'is_lexical_word'
> 
>     * [ ]  FAILED tests/tools/MatplotlibTool_test.py::test_call - TypeError: MatplotlibTool.**call**() missing 1 required positional argument: 'y_data'
> 
>     * [ ]  FAILED tests/tools/RequestsTool_test.py::test_call - AttributeError: 'int' object has no attribute 'lower'
> 
>     * [x]  FAILED tests/tools/TextLength_test.py::test_call - TypeError: TextLengthTool.**call**() takes 2 positional arguments but 3 were given

**Comment by MichaelDecent** [comment]
`textstat` do not have this function `textstat.is_lexical_word(word)]`  i made a little research and  `nltk` or `spaCy` would be the appropriate libraries to perform lexical word identification. here is the proposed function 
```
def count_lexical_words(text: str) -> int:
    """
    Counts the number of lexical words (nouns, verbs, adjectives, adverbs) in the text.

    Args:
        text (str): The text to analyze.

    Returns:
        int: The number of lexical words in the text.
    """
    # Tokenize the text into words
    words = word_tokenize(text)
    
    # Get part of speech tags for each word
    pos_tags = pos_tag(words)
    
    # Lexical categories: nouns, verbs, adjectives, adverbs
    lexical_pos = {'NN', 'NNS', 'NNP', 'NNPS', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 
                   'JJ', 'JJR', 'JJS', 'RB', 'RBR', 'RBS'}
    
    # Filter words that are in lexical categories
    lexical_words = [word for word, pos in pos_tags if pos in lexical_pos]
    
    return len(lexical_words)
```
