### ISSUE TITLE
[EPIC 4] Test case hygiene - parameterization/skipifs/code

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-sdk#404]
- [ ] #469
Add `skipIf` to tests that depend on environment variables or external dependencies.
- [x] #470
Identify and parameterize test cases for LLMs and classes with multiple options to ensure comprehensive coverage.
- [x] #471
Refactor setup into reusable pytest fixtures to improve test maintainability and reduce duplication.

**Comment by MichaelDecent** [comment]
Currently in progress.

completed `test fixtures` and `skipifs` for `swarmauri pkgs`
