### ISSUE TITLE
Reference latest documentation and Update allowed_models lists for LLM Models

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-sdk#421]
- [ ] AI21StudioModel
- [ ] AnthropicModel
- [ ] Anthropic Tool Model
- [ ] Cohere Model
- [ ] Cohere Tool Model
- [ ] DeepInfra Model
- [ ] DeepSeek Model
- [ ] GeminiPro Model
- [ ] Gemini Tool Model
- [ ] Groq Model
- [ ] Groq Tool Model
- [ ] Mistral Model
- [ ] Mistra Tool Model
- [ ] OpenAI Image Generator
- [ ] OpenAI Model
- [ ] OpenAI Tool Model
- [ ] Perplexity Model
- [ ] ShuttleAI Model
- [ ] ShuttleAI Tool Model

**Comment by cobycloud** [comment]
include links to the model documentation in the docstrings of the models

**Comment by 3rd-Son** [comment]
I have started working on this

**Comment by 3rd-Son** [comment]
> * [X]  AnthropicModel
> * [X]  Anthropic Tool Model
> * [X]  Cohere Model

**Comment by 3rd-Son** [comment]
> include links to the model documentation in the docstrings of the models

Should I include anything else in the doctrings, or just the link to the model's documentation?
