### ISSUE TITLE
[Feature Request]: standard/metrics/concrete/MissingnessMetric.py

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#486]
### Feature Name

standard/metrics/concrete/MissingnessMetric.py

### Feature Description

A metric that evaluates a set to determine the Missingness.

### Motivation

Tracking missingness in a code repository provides insight into data quality and completeness. Missing data can cause failures in automated scripts, lead to inaccurate results in testing, or trigger unexpected behavior in production environments. By analyzing missingness, teams can identify fields or variables that lack critical values and take corrective actions—whether by adding appropriate defaults, filling gaps, or alerting responsible developers. This becomes particularly important in projects where configuration files, documentation, or datasets are central to the code's operation. Regular monitoring of missingness ensures that gaps in critical information are detected early, reducing the risk of software bugs, failed deployments, and compromised functionality in production environments.

### Potential Solutions

```python
# Creating a sample dataset for missingness
data_missingness = pd.DataFrame({
    'Age': [25, 30, None, 45, 28, None, 32, 35, None]
})

# Calculating missingness
total_values_missingness = data_missingness['Age'].count() + data_missingness['Age'].isna().sum()
missing_values = data_missingness['Age'].isna().sum()
missingness_percentage = (missing_values / total_values_missingness) * 100

# Displaying the result for missingness
missingness_percentage

```

### Affected Areas

None

### Priority

Low

**Comment by 3rd-Son** [comment]
made a PR for this #756
