### ISSUE TITLE
research third party embedding APIs

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#49]
- [ ] openai
- [ ] perplexity
- [ ] mixtral
- [ ] gemini
- [ ] anthropic
- [ ] cohere

**Comment by cobycloud** [comment]
provide a list of documentation for the embedding APIs listed above

**Comment by abdulsamodazeez** [comment]
Openai: https://platform.openai.com/docs/guides/embeddings/use-cases

Mistral: https://docs.mistral.ai/capabilities/embeddings/

Gemini:

- https://ai.google.dev/gemini-api/docs/embeddings
- https://ai.google.dev/api/embeddings

Anthropic: https://docs.anthropic.com/en/docs/build-with-claude/embeddings

Cohere:
- https://docs.cohere.com/docs/embeddings
- https://docs.cohere.com/reference/embed
