### ISSUE TITLE
[Feature Request]: PyPDFTKParser

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#498]
### Feature Name

swarmauri_community/parsers/concrete/PyPDFTKParser.py

### Feature Description

Using PyPDFTK, extract data fields from PDF files

### Motivation

To enable parsing of pdf documents

### Potential Solutions

```python
# pip install pypdftk
import pypdftk
from typing import Any, Union, List, Literal
from swarmauri.parsers.base.ParserBase import ParserBase
from swarmauri.core.documents.IDocument import IDocument
from swarmauri.standard.documents.concrete.Document import Document

class PyPDFTKParser(ParserBase):
    """
    Parser for reading and extracting data fields from PDF files using PyPDFTK.
    """
    type: Literal['PyPDFTKParser'] = 'PyPDFTKParser'
    
    def parse(self, source: str) -> List[IDocument]:
        fields = pypdftk.dump_data_fields(source)
        return [Document(content=str(fields))]
        
        
        
```

### Affected Areas

None

### Priority

Low

### Required Files

- [ ] Test File
- [ ] Component File

**Comment by wpn10** [comment]
A pull request has been submitted to resolve this issue:  [https://github.com/swarmauri/swarmauri-sdk/pull/552](PR)

**Comment by wpn10** [comment]
Hi,
I’ve tested all my PyPDFTKParser test cases locally. The build is failing due to a missing weaviate module in another test, which is unrelated to my changes. Please let me know if there is anything I can do regarding the current change.

Thank you!

**Comment by cobycloud** [comment]
This PR by @wpn10 is designed to resolve: https://github.com/swarmauri/swarmauri-sdk/pull/552
