### ISSUE TITLE
[Bug]:  Embedding; OpenAI API connection error

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#521]
### Describe the Bug

Currently we are having problems with tests running embedding using OpenAIEmbedding on the workflow.

![image](https://github.com/user-attachments/assets/89841ee6-0064-4fc8-87ce-ee11c608cfc3)

They keep giving a connection error in the workflow,

locally they seem to be working correctly :

![image](https://github.com/user-attachments/assets/3258a31e-a2c0-46a9-a50e-91c4af87a6ea)

(*this test was taken on Ubuntu 22.04 Linux PC*)

### Steps to Reproduce

Run the test on the workflow run

### Software Version

Latest (Nightly Build)

### Python Version

Python 3.10

### Relevant Logs or Error Output

```shell
FAILED pkgs/swarmauri/tests/unit/embeddings/OpenAIEmbedding_unit_test.py::test_infer_vector - openai.APIConnectionError: Connection error.
```

### Additional Context (Optional)

Any progress you make will be appreciated if commented :). Thank you!

### Confirmation

- [X] I have searched the existing issues for this bug.
- [X] I have provided all necessary information to reproduce the bug.

**Comment by 3rd-Son** [comment]
for this to work, I have added `dotenv` to the test file so that the `OPENAI_API_KEY` can be properly used
