### ISSUE TITLE
[Technical Debt]: Files Integrity

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#538]
### Affected Component

/

### Motivation

Due to the current refactor of the SDK,  some files might be lost.

### Potential Solutions

[all.txt](https://github.com/user-attachments/files/17164104/all.txt)

Attached to this comment is  a file that contains  patterns  of all files  that were in the SDK before refactor.

For this issue to be regarded as done:

- A file containing descriptive logs of each pattern and the file it matches should be  added *example: pattern: ` setup`  File: `setup.py`*
- If files are found missing they should be added in a comment

### Affected Areas

- [X] Core
- [X] Standard/Base
- [X] Standard/Concrete
- [X] Community
- [X] Experimental

**Comment by MichaelDecent** [comment]
- [ ]    "SimpleSwarmAgent": [],
- [ ]     "NmfEmbeddinga": [],
- [ ]     "GithubWebhookTool": [],
- [ ]     "PaCAMP_test": [],
- [ ]     "ChainProcessingStrategy": [],
- [ ]     "GunningFogIndexTool": [],
- [ ]     "ChatSwarmAgent": [],
- [ ]     "ISaveLoadStore": [],
- [ ]     "TFIDFVectorStorea": [],
- [ ]     "combined_standard.json": [],
- [ ]     "TimeOnTaskMetric": [],
- [ ]     "GunningFogIndex_test": [],
- [ ]     "LeptonAIModel_test": [],
- [ ]     "SystemUsabilityScaleMetric": [],
- [ ]     "GithubMilestoneTool_test": [],
- [ ]     "TaskSuccessRateMetric": [],
- [ ]     "IVectorRetrieve": [],
- [ ]     "DGLVectorizer": [],
- [ ]     "EmbeddedBase": [],
- [ ]     "GeminiEmbedding_test": [],
- [ ]     "RequestTool_test": [],
- [ ]     "QdrantVectorStore_test": [],
- [ ]     "WeaviateVectorStore": [],
- [ ]     "LimitedSizeConversation": [],
- [ ]     "ShuttleAIToolModel_test": [],
- [ ]     "IAgentDocument": [],
- [ ]     "CohereToolModel_test": [],
- [ ]     "QdrantVectorStore": [],
- [ ]     "SystemContextBase": [],
- [ ]     "TFIDFVectorizer": [],
- [ ]     "demo.pdf": [],
- [ ]     "SaveLoadStoreBase": [],
- [ ]     "pytest.ini": [],
- [ ]     "GithubLabelTool_test": [],
- [ ]     "RequestsTool_test": [],
- [ ]     "IModel": [],
- [ ]     "GithubGistTool_test": [],
- [ ]     "ParameterTool_test": [],
- [ ]     "MultiPartyChatSwarmAgent": [],
- [ ]     "AnthropicToolModel_test": [],
- [ ]     "ChromaDBVectorStore": [],
- [ ]     "AzureGPT": [],
- [ ]     "HitRateAtK": [],
- [ ]     "combined_experimental.json": [],
- [ ]     "ChromadbVectorStore_test": [],
- [ ]     "ICalculateMetric": [],
- [ ]     "combined_community.json": [],
- [ ]     "GithubMilestoneTool": [],
- [ ]     "combined_core.json": [],
- [ ]     "BERTVectorStore": [],
- [ ]     "SingleCommandAgent": [],
- [ ]     "combined_core_standard.json": [],
- [ ]     "NMFVectorizer": [],
- [ ]     "FunctionMessage_Test": [],
- [ ]     "tool_test": [],
- [ ]     "combined_paths.json": [],
- [ ]     "ImpressionAtK": [],
- [ ]     "TFIDFEmbedding": [],
- [ ]     "ChromadbVectorStore_test-checkpoint": [],
- [ ]     "SimpleVector": [],
- [ ]     "SystemContextMixin": [],
- [ ]     "AgentRetrieveBase": [],
- [ ]     "ConversationAgentBase": [],
- [ ]     "GithubCollaboratorTool": [],
- [ ]     "ISwarmAgentRegistrationAPI": [],
- [ ]     "MatrixProcessingStrategy": [],
- [ ]     "ThresholdMeanMetric": [],
- [ ]     "VectorStoreAgentBase": [],
- [ ]     "A_test": [],
- [ ]     "HtmlTagStripParser": [],
- [ ]     "ParameterTool": [],
- [ ]     "IChainOrderStrategy": [],
- [ ]     "FunctionMessage_testa": [],
- [ ]     "NamedAgentBase": [],
- [ ]     "MLMVectorStorea": [],
- [ ]     "FaissVectorStore": [],
- [ ]     "_test": [],
- [ ]     "IAgentName": [],
- [ ]     ".DS_Store": [],
- [ ]     "MLMVectorStore": [],
- [ ]     "SimpleSentenceChunker": [],
- [ ]     "GithubGistTool": [],
- [ ]     "ChromadbVectorStore": [],
- [ ]     "GithubCollaboratorTool_test": [],
- [ ]     "GunningFogIndex": [],
- [ ]     "IAgentRetriever": [],
- [ ]     "MarkdownParser": [],
- [ ]     "TFIDFParser": [],
- [ ]     "IAggMeasurements": [],
- [ ]     "MultiPartyToolAgent": [],
- [ ]     "IChainProcessingStrategy": [],
- [ ]     "MarkdownParser_test": [],
- [ ]     "BaseComponent": [],
- [ ]     "HTMLTagStripParsera": [],
- [ ]     "03_code_hygiene": [],
- [ ]     "NMFEmbedding": [],
- [ ]     "ThresholdMetricBase": [],
- [ ]     "GithubWebhookTool_test": [],
- [ ]     "SpatialDocVectorizer": [],
- [ ]     "BeautifulSoupElementParserTool_test": [],
- [ ]     "MlmEmbeddinga": [],
- [ ]     "StaticValueMetric": [],
- [ ]     "DocumentAgentBase": [],
- [ ]     "AggregateMetricBase": [],
- [ ]     "combined_examples.json": [],
- [ ]     "BERTEmbeddingVectorizer": [],
- [ ]     "SystemContextAgentBase": [],
- [ ]     "combined_content.json": [],
- [ ]     "VectorDocumentStoreRetrieveBase": [],
- [ ]     "GenerativeRagAgent": [],
- [ ]     "Doc2VecVectorizer": [],
- [ ]     "build.sh": [],
- [ ]     "GithubLabelTool": [],
- [ ]     "IResetMetric": [],
- [ ]     "ChainOrderStrategyBase": [],
- [ ]     "TFIDFVectorStore": [],
- [ ]     "EmbeddedDocument": [],
- [ ]     "ToolAgentBase": [],
- [ ]     "MLMEmbedding": [],
- [ ]     "ChainProcessingStrategyBase": [],
- [ ]     "TfidfEmbeddinga": [],
- [ ]     "MatrixOrderStrategy": [],
- [ ]     "ModelBase": [],
- [ ]     "VectorDocumentStoreBase": [],
- [ ]     "CalculateMetricBase": [],
- [ ]     "BasePromptMatrix": [],
- [ ]     "ChainOrderStrategy": [],
- [ ]     "MLMVectorizer": [],
- [ ]     "get_docx_links": [],
- [ ]     "MistralEmbedding_test": [],
- [ ]     "LimitedSystemContextConversation": [],
- [ ]     "IEmbed": [],
- [ ]     "RequestTool": [],
- [ ]     "ResetableMetricBase": [],
- [ ]     "StateChain": []

**Comment by 3rd-Son** [comment]
> Let start by confirm these files.
> 
> * [ ]     "GunningFogIndex_test": [],
> * [ ]      "TemperatureConverterTool_test": [],
> * [ ]      "MlmVectorStore_test": [],
> * [ ]      "XMLParser_test": [],
> * [ ]      "TextLength_test": [],
> * [ ]      "MultiPartyToolAgent": [],
> * [ ]      "ChainOrderStrategy": [],
> * [ ]      "GithubMilestoneTool_test": [],
> * [ ]      "MistralSchemaConverter_test": [],
> * [ ]      "FaissVectorStore": [],
> * [ ]      "RatioOfSumsMetric_test": [],
> * [ ]      "StateChain": [],
> * [ ]      "HTMLTagStripParser_test": [],
> * [ ]      "OpenAISchemaConverter_test": [],
> * [ ]      "Doc2VecVectorStore_test": [],
> * [ ]      "_test": [],
> * [ ]      "ChatSwarmAgent": [],
> * [ ]      "BERTVectorStore": [],
> * [ ]      "TestTool_test": [],
> * [ ]      "IChainOrderStrategy": [],
> * [ ]      "GunningFogIndex": [],
> * [ ]      ".DS_Store": [],
> * [ ]      "ChainProcessingStrategy": [],
> * [ ]      "ChromaDBVectorStore": [],
> * [ ]      "SpatialDocEmbedding_test": [],
> * [ ]      "DeepInfraModel_test": [],
> * [ ]      "CalculatorTool_test": [],
> * [ ]      "ManhattanDistance_test": [],
> * [ ]      "MaxSystemContextConversation_test": [],
> * [ ]      "ChainProcessingStrategyBase": [],
> * [ ]      "IChainProcessingStrategy": [],
> * [ ]      "ContextChain_test": [],
> * [ ]      "AnthropicModel_test": [],
> * [ ]      "NamedAgentBase": [],
> * [ ]      "pytest.ini": [],
> * [ ]      "tool_test": [],
> * [ ]      "PaCAMP_test": [],
> * [ ]      "ChainOrderStrategyBase": [],
> * [ ]      "ChebyShevDistance_test": [],
> * [ ]      "EuclideanDistance_test": [],
> * [ ]      "ToolAgentBase": [],
> * [ ]      "Vector_test": [],
> * [ ]      "IModel": [],
> * [ ]      "ThresholdMeanMetric": [],
> * [ ]      "HTMLTagStripParsera": [],
> * [ ]      "IAggMeasurements": [],
> * [ ]      "GroqToolModel_test": [],
> * [ ]      "MLMVectorizer": [],
> * [ ]      "combined_paths.json": [],
> * [ ]      "MdSnippetChunker_test": [],
> * [ ]      "Document_test": [],
> * [ ]      "AutomatedReadabilityIndex_test": [],
> * [ ]      "CohereModel_test": [],
> * [ ]      "JaccardIndexDistance_test": [],
> * [ ]      "TFIDFParser": [],
> * [ ]      "MeanMetric_test": [],
> * [ ]      "EmbeddedDocument": [],
> * [ ]      "ImportMemoryModuleTool_test": [],
> * [ ]      "ChromadbVectorStore_test": [],
> * [ ]      "SystemContextAgentBase": [],
> * [ ]      "GeminiEmbedding_test": [],
> * [ ]      "GroqModel_test": [],
> * [ ]      "SpatialDocEmbedding1_test": [],
> * [ ]      "DelimiterBasedChunker_test": [],
> * [ ]      "ChiSquaredDistance_test": [],
> * [ ]      "ISwarmAgentRegistrationAPI": [],
> * [ ]      "FleschKincaid_test": [],
> * [ ]      "FunctionMessage_test": [],
> * [ ]      "FirstImpressionMetric_test": [],
> * [ ]      "BaseComponent": [],
> * [ ]      "SlidingWindowChunker_test": [],
> * [ ]      "MistralModel_test": [],
> * [ ]      "GithubGistTool_test": [],
> * [ ]      "TimeOnTaskMetric": [],
> * [ ]      "GithubLabelTool_test": [],
> * [ ]      "combined_core.json": [],
> * [ ]      "GroqSchemaConverter_test": [],
> * [ ]      "GithubMilestoneTool": [],
> * [ ]      "NMFVectorizer": [],
> * [ ]      "GithubCollaboratorTool_test": [],
> * [ ]      "GenerativeRagAgent": [],
> * [ ]      "MLMVectorStore": [],
> * [ ]      "BeautifulSoupElementParserTool_test": [],
> * [ ]      "TFIDFVectorizer": [],
> * [ ]      "KeywordExtractorParser_test": [],
> * [ ]      "WeatherTool_test": [],
> * [ ]      "CalculateMetricBase": [],
> * [ ]      "GeminiToolModel_test": [],
> * [ ]      "MLMVectorStorea": [],
> * [ ]      "Conversation_test": [],
> * [ ]      "ThresholdMetricBase": [],
> * [ ]      "DeepSeekModel_test": [],
> * [ ]      "QdrantVectorStore_test": [],
> * [ ]      "NmfEmbeddinga": [],
> * [ ]      "BasePromptMatrix": [],
> * [ ]      "IVectorRetrieve": [],
> * [ ]      "TfidfVectorStore_test": [],
> * [ ]      "SpatialDocEmbedding2_test": [],
> * [ ]      "LimitedSizeConversation": [],
> * [ ]      "OpenAIToolModel_test": [],
> * [ ]      "MistralToolModel_test": [],
> * [ ]      "HaversineDistance_test": [],
> * [ ]      "build.sh": [],
> * [ ]      "SorensenDiceDistance_test": [],
> * [ ]      "GunningFogIndexTool": [],
> * [ ]      "VectorDocumentStoreRetrieveBase": [],
> * [ ]      "GeminiSchemaConverter_test": [],
> * [ ]      "ShuttleAIToolModel_test": [],
> * [ ]      "ColemanLiauIndex_test": [],
> * [ ]      "QdrantVectorStore": [],
> * [ ]      "ChainStep_test": [],
> * [ ]      "ZeroMetric_test": [],
> * [ ]      "MLMEmbedding": [],
> * [ ]      "ICalculateMetric": [],
> * [ ]      "RequestTool_test": [],
> * [ ]      "StaticMetric_test": [],
> * [ ]      "OpenAIEmbedding_test": [],
> * [ ]      "PromptMatrix_test": [],
> * [ ]      "AgentMessage_test": [],
> * [ ]      "Doc2VecVectorizer": [],
> * [ ]      "SystemContextMixin": [],
> * [ ]      "SpatialDocVectorizer": [],
> * [ ]      "MatplotlibTool_test": [],
> * [ ]      "MistralEmbedding_test": [],
> * [ ]      "SimpleSentenceChunker": [],
> * [ ]      "TFIDFEmbedding": [],
> * [ ]      "MultiPartyChatSwarmAgent": [],
> * [ ]      "03_code_hygiene": [],
> * [ ]      "ParameterTool_test": [],
> * [ ]      "SessionCacheConversation_test": [],
> * [ ]      "HtmlTagStripParser": [],
> * [ ]      "NmfEmbedding_test": [],
> * [ ]      "ToolAgent_test": [],
> * [ ]      "GunningFogTool_test": [],
> * [ ]      "ImpressionAtK": [],
> * [ ]      "RagAgent_test": [],
> * [ ]      "DocumentAgentBase": [],
> * [ ]      "PatternMatchingMetric_test": [],
> * [ ]      "MatrixOrderStrategy": [],
> * [ ]      "combined_standard.json": [],
> * [ ]      "SystemContextBase": [],
> * [ ]      "PhoneNumberExtractorParser_test": [],
> * [ ]      "Md2HtmlParser_test": [],
> * [ ]      "Doc2VecEmbedding_test": [],
> * [ ]      "RegExParser_test": [],
> * [ ]      "CohereSchemaConverter_test": [],
> * [ ]      "MatrixProcessingStrategy": [],
> * [ ]      "RequestsTool_test": [],
> * [ ]      "ISaveLoadStore": [],
> * [ ]      "GithubCollaboratorTool": [],
> * [ ]      "EmbeddedBase": [],
> * [ ]      "HumanMessage_test": [],
> * [ ]      "AgentRetrieveBase": [],
> * [ ]      "TfidfEmbedding_test": [],
> * [ ]      "GithubLabelTool": [],
> * [ ]      "MarkdownParser_test": [],
> * [ ]      "AnthropicToolModel_test": [],
> * [ ]      "AnthropicSchemaConverter_test": [],
> * [ ]      "A_test": [],
> * [ ]      "combined_core_standard.json": [],
> * [ ]      "ResetableMetricBase": [],
> * [ ]      "IAgentDocument": [],
> * [ ]      "ParameterTool": [],
> * [ ]      "ConversationAgentBase": [],
> * [ ]      "DGLVectorizer": [],
> * [ ]      "ShuttleAISchemaConverter_test": [],
> * [ ]      "TextBlobSentenceParser_test": [],
> * [ ]      "CohereToolModel_test": [],
> * [ ]      "MatplotlibCsvTool_test": [],
> * [ ]      "PerplexityModel_test": [],
> * [ ]      "typing_test": [],
> * [ ]      "MinkowskiDistance_test": [],
> * [ ]      "OpenRouterModel_test": [],
> * [ ]      "BeautifulSoupElementParser_test": [],
> * [ ]      "get_docx_links": [],
> * [ ]      "FunctionMessage_Test": [],
> * [ ]      "VectorDocumentStoreBase": [],
> * [ ]      "FunctionMessage_testa": [],
> * [ ]      "TaskSuccessRateMetric": [],
> * [ ]      "SaveLoadStoreBase": [],
> * [ ]      "TextBlobNounParser_test": [],
> * [ ]      "IEmbed": [],
> * [ ]      "LimitedSystemContextConversation": [],
> * [ ]      "SingleCommandAgent": [],
> * [ ]      "JSONRequestsTool_test": [],
> * [ ]      "AccessibilityToolkit_test": [],
> * [ ]      "PythonParser_test": [],
> * [ ]      "SimpleSwarmAgent": [],
> * [ ]      "OpenAIModel_test": [],
> * [ ]      "TfidfEmbeddinga": [],
> * [ ]      "WeaviateVectorStore": [],
> * [ ]      "AdditionTool_test": [],
> * [ ]      "QAAgent_test": [],
> * [ ]      "VectorStoreAgentBase": [],
> * [ ]      "CosineDistance_test": [],
> * [ ]      "Prompt_test": [],
> * [ ]      "AI21StudioModel_test": [],
> * [ ]      "AggregateMetricBase": [],
> * [ ]      "TFIDFVectorStorea": [],
> * [ ]      "ChromadbVectorStore_test-checkpoint": [],
> * [ ]      "CodeInterpreterTool_test": [],
> * [ ]      "SimpleConversationAgent_test": [],
> * [ ]      "ChromadbVectorStore": [],
> * [ ]      "GithubWebhookTool": [],
> * [ ]      "MlmEmbeddinga": [],
> * [ ]      "FleschReadingEase_test": [],
> * [ ]      "Toolkit_test": [],
> * [ ]      "demo.pdf": [],
> * [ ]      "AzureGPT": [],
> * [ ]      "combined_experimental.json": [],
> * [ ]      "StaticValueMetric": [],
> * [ ]      "IResetMetric": [],
> * [ ]      "Parameter_test": [],
> * [ ]      "SystemUsabilityScaleMetric": [],
> * [ ]      "IAgentName": [],
> * [ ]      "URLExtractorParser_test": [],
> * [ ]      "combined_content.json": [],
> * [ ]      "RequestTool": [],
> * [ ]      "LeptonAIModel_test": [],
> * [ ]      "ModelBase": [],
> * [ ]      "HitRateAtK": [],
> * [ ]      "combined_community.json": [],
> * [ ]      "TFIDFVectorStore": [],
> * [ ]      "MlmEmbedding_test": [],
> * [ ]      "SystemMessage_test": [],
> * [ ]      "GithubGistTool": [],
> * [ ]      "SqliteVectorStore_test": [],
> * [ ]      "IAgentRetriever": [],
> * [ ]      "combined_examples.json": [],
> * [ ]      "GeminiProModel_test": [],
> * [ ]      "NMFEmbedding": [],
> * [ ]      "SentenceChunker_test": [],
> * [ ]      "MarkdownParser": [],
> * [ ]      "LevenshteinDistance_test": [],
> * [ ]      "GithubWebhookTool_test": [],
> * [ ]      "FixedLengthChunker_test": [],
> * [ ]      "SquaredEuclideanDistance_test": [],
> * [ ]      "SimpleVector": [],
> * [ ]      "MaxSizeConversation_test": [],
> * [ ]      "BERTEmbeddingVectorizer": [],
> * [ ]      "PromptTemplate_test": [],
> * [ ]      "CanberraDistance_test": [],
> * [ ]      "CodeExtractorTool_test": [],
> * [ ]      "OpenAPISpecParser_test": [],
> * [ ]      "PromptGenerator_test": []

@MichaelDecent this files you listed, are they exactly the same with the ones in all.txt?

**Comment by 3rd-Son** [comment]
@MichaelDecent these files you listed, are they exactly the same with ones in the all.txt?

**Comment by MichaelDecent** [comment]
the names of files once listed are among the ` all.txt` which were present the sdk before refactoring but not found the our current sdk after refactoring, we still have to reconfirm if these listed  file exist in our current sdk

**Comment by RafaelJohn9** [comment]
Logs: 
[file_checker.log](https://github.com/user-attachments/files/17164123/file_checker.log)

Missing files:
[missing.log](https://github.com/user-attachments/files/17164130/missing.log)

**Comment by RafaelJohn9** [comment]
most were renamed only missing is `Lepton_AI_tests`
