### ISSUE TITLE
add support for sqlite-vec

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#56]
using [sqlite3-vec](https://alexgarcia.xyz/sqlite-vec/python.html),
create a new test file for this class in `tests/vector_stores/concrete/SqliteVectorStore_test.py` and
create a new vector store class in `standard/vector_stores/concrete/SqliteVectorStore.py`

**Comment by cobycloud** [comment]
use `tests/vector_stores/concrete/MLMVectorStore_test.py` as a template

**Comment by MichaelDecent** [comment]
Okay!

**Comment by MichaelDecent** [comment]
`MLMVectorStore_test.py` not found in concrete folder, this is what i have in the repo `tests/vector_stores/MLMVectorStore_test.py`

**Comment by cobycloud** [comment]
typo use: https://github.com/swarmauri/swarmauri-sdk/blob/master/tests/vector_stores/MlmVectorStore_test.py
