### ISSUE TITLE
[Feature Request]: Support for openai/whisper-large-v3 - sst

### ISSUE THREAD

**Issue by 3rd-Son** [swarmauri/swarmauri-sdk#592]
### Feature Name

openai/whisper-large-v3

### Feature Description

- Research and implement whisper-larger-v3
- Whisper is a state-of-the-art model for automatic speech recognition (ASR) and speech translation, proposed in the paper [Robust Speech Recognition via Large-Scale Weak Supervision](https://huggingface.co/papers/2212.04356) by Alec Radford et al. from OpenAI. Trained on >5M hours of labeled data, Whisper demonstrates a strong ability to generalise to many datasets and domains in a zero-shot setting.

### Motivation

This model is used for automatic speech recognition (ASR) and speech translation and adding this model to the sdk will allow users to be able to use it from the sdk.
For more info on the model, check out https://huggingface.co/openai/whisper-large-v3

### Potential Solutions

Whisper large-v3 is supported in Hugging Face 🤗 Transformers.
Here is the link https://huggingface.co/openai/whisper-large-v3

### Affected Areas

None

### Priority

Low

### Required Files

- [X] Test File
- [X] Component File

**Comment by MichaelDecent** [comment]
`whisper-larger-v3-sst` happens to be an Open AI model that isn't yet supported by the Open AI  Api. currently only `whisper-larger-v2` is supported which has been implemented the swarmauri sdk
