### ISSUE TITLE
[Feature Request]: DeepInfraTextToImageModel

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#638]
### Feature Name

DeepInfraTextToImageModel

### Feature Description

Using deep infra as a provider and their text-to-image api, create a text-to-image model.

### Motivation

 provide support for text-to-image generation

### Additional Context (optional)

https://deepinfra.com/models/text-to-image

### Affected Areas

None

### Priority

Low

### Required Files

- [ ] Test File
- [ ] Component File

**Comment by 3rd-Son** [comment]
@cobycloud in which of the pkgs should this be?
