### ISSUE TITLE
[Bug]: PlayHTModel - allowed voices

### ISSUE THREAD

**Issue by cobycloud** [swarmauri/swarmauri-sdk#765]
### Describe the Bug

![image](https://github.com/user-attachments/assets/3c2fbff4-a3f8-4621-9616-c602898e83d9)

### Steps to Reproduce

```python
from swarmauri.llms.concrete.PlayHTModel import PlayHTModel

 playht_model = PlayHTModel(user_id='', api_key='', voice='Alice')
 ```

### Software Version

Other (specify in additional context)

### Python Version

Python 3.12

### Environment Details

windows

### Confirmation

- [x] I have searched the existing issues for this bug.
- [x] I have provided all necessary information to reproduce the bug.

**Comment by cobycloud** [comment]
Code should:

1. Use voice interfaces to get JSON payload for voices supported
![image](https://github.com/user-attachments/assets/ab04e145-da4b-43b7-b033-e5e1551b21f4)
2. An example record looks like this:
```json
 {
    "id": "s3://voice-cloning-zero-shot/d82d246c-148b-457f-9668-37b789520891/adolfosaad/manifest.json",
    "name": "Adolfo",
    "sample": "https://parrot-samples.s3.amazonaws.com/kettle/adolfo.wav",
    "accent": "american",
    "age": "adult",
    "gender": "male",
    "language": "English (US)",
    "language_code": "en-US",
    "loudness": "neutral",
    "style": "narrative",
    "tempo": "fast",
    "texture": "thick",
    "is_cloned": false,
    "voice_engine": "PlayHT2.0"
  }
  ```

When our consumers uses `voice` as an attribute with the PlayHTModel, they are referencing the name of the voice model, not the id of the voice model. Then we use the name of the voice model to find the ID of the voice model. Once we have the ID of the voice model through this means, then we continue business as usual.


Our consumers shouldn't be expected to know the full ID of the model as its not very human readable.

**Comment by MichaelDecent** [comment]
Well Noted!. i will get it fixed

**Comment by MichaelDecent** [comment]
[](https://github.com/swarmauri/swarmauri-sdk/pull/767)
