### ISSUE TITLE
[Refactoring Request]: Refactoring of the allowed_models in WhisperLargeModel

### ISSUE THREAD

**Issue by 3rd-Son** [swarmauri/swarmauri-sdk#921]
### Affected Component

swarmauri/llms/whisperLargeModel

### Motivation

To check for updates in the allowed_model list in `WhisperLargeModel`
This can be removing of depreciated models and adding new models

### Potential Refactoring Approach

Check the documentation so you can see the depreciated models and newly added models.

### Affected Areas

- [X] Swarmauri

### Priority

Low

**Comment by Lavesh-Akhadkar** [comment]
Hi @3rd-Son 

Can you explain in detail about what exact changes are required?

From my understanding there are no required changes in the allowed_model list of WhisperLargeModel as the class is implemented only for openai/whisper-large-v3 and the huggingface inference endpoint used is also only for openai/whisper-large-v3 meaning that there is only one model supported which is openai/whisper-large-v3 and it is not deprecated.

**Comment by 3rd-Son** [comment]
Yea, you are correct @Lavesh-Akhadkar 
If you notice, I created alot of tickets along side this one.
If you check the documentation and see that the allowed_models have not been changed (that is: no models have been depreciated or added), then it's fine

The tickets were created so we can have a quick check on all the models in the `swarmuari/llms` and update them.

I don't know if you understand this @Lavesh-Akhadkar

**Comment by Lavesh-Akhadkar** [comment]
Ah got it @3rd-Son didn't notice the other similar tickets before this one. I guess this issue can be closed then as there are no changes in the allowed_models of WhisperLargeModel.

**Comment by 3rd-Son** [comment]
Yea bro. 
I will close this one now.
you can go on and work on the other tickets, for each of them, use a different branch and then create a PR
